### ISSUE TITLE
Updating Workshop Content for Participants

### ISSUE THREAD

**Issue by rstarowicz** [dlab-berkeley/Intro-Qualtrics#4]
We would like to remove the folder of downloadable materials for embedded links to materials that are easier to modify and update regularly.

(1) [D-Lab Introduction to Qualtrics Workshop Slides](https://docs.google.com/presentation/d/1hd_IzJcmgriZ6CsD7LRNFWa22Qgs507oZnS_kdBEMGo/edit#slide=id.p)

(2) [D-Lab Introduction to Qualtrics Challenge Problem](https://docs.google.com/document/d/1TexH674r9eQKLWa9EyJnuzdFb71KfwEnEr_HVVElOM0/edit?usp=sharing)

**Comment by pssachdeva** [comment]
Closed by #9
